name: Post dialect to X

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: dialect-post-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 1) 会話文を生成して在庫を移動
      - name: Generate post & move item
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          node generate_and_move.mjs > post.txt
          {
            echo "POST_BODY<<EOF"
            cat post.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          echo "Generated:"
          cat post.txt

      # 2) X に投稿（index.mjs は process.env.POST_BODY を読む想定）
      - name: Run bot (post to X)
        if: ${{ steps.gen.outputs.POST_BODY != '' }}
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          POST_BODY: ${{ steps.gen.outputs.POST_BODY }}
        run: |
          set -euo pipefail
          node -e "
            const { TwitterApi } = require('twitter-api-v2');
            const client = new TwitterApi({
              appKey: process.env.X_API_KEY,
              appSecret: process.env.X_API_SECRET,
              accessToken: process.env.X_ACCESS_TOKEN,
              accessSecret: process.env.X_ACCESS_SECRET,
            });
            (async () => {
              const me = await client.v2.me();
              console.log('Posting as @' + me.data.username);
            })().catch(e => { console.error(e); process.exit(1); });
          "
          node index.mjs

      # 3) 在庫移動などの変更をコミット
      - name: Commit moved/posted changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "move posted items & logs"
          git push
