name: Post dialect to X

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと（UTC基準）
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: dialect-post-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 1) 会話文を生成して在庫を移動（post.txt を出しつつ、出力を steps.gen.outputs.POST_BODY に渡す）
      - name: Generate post & move item
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          node generate_and_move.mjs > post.txt
          echo "Generated:"
          cat post.txt
          {
            echo "POST_BODY<<EOF"
            cat post.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # 2) X に投稿（成功マーカー "Tweet OK:" を強制チェック）
      - name: Run bot (post to X)
        if: ${{ steps.gen.outputs.POST_BODY != '' }}
        env:
          X_API_KEY:       ${{ secrets.X_API_KEY }}
          X_API_SECRET:    ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN:  ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          POST_BODY:       ${{ steps.gen.outputs.POST_BODY }}
        run: |
          set -euo pipefail
          node index.mjs | tee post.log
          # 成功マーカーがなければ失敗扱い
          grep -q "Tweet OK:" post.log

      # 3) 在庫移動などの変更をコミット（投稿失敗時はここに来ない）
      - name: Commit moved/posted changes
        run: |
          set -euo pipefail
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "move posted items & logs"
          git push
