name: Post dialect to X

on:
  schedule:
    - cron: "*/30 * * * *"   # 30蛻・＃縺ｨ・・TC・・
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: dialect-post
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 1) 莨夊ｩｱ譁・ｒ逕滓・・・惠蠎ｫ繧堤ｧｻ蜍・
      - name: Generate post & move item
        id: gen
        run: |
          node generate_and_move.mjs > post.txt
          echo "POST_BODY<<'EOF'" >> $GITHUB_OUTPUT
          cat post.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 2) X 縺ｫ謚慕ｨｿ・・ndex.js 縺ｯ POST_BODY 繧貞━蜈井ｽｿ逕ｨ・・
      - name: Run bot (post to X)
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          POST_BODY: ${{ steps.gen.outputs.POST_BODY }}
        run: |
          if [ -z "$POST_BODY" ]; then
            echo "No POST_BODY generated. Skip posting."
            exit 1
          fi
          node index.js

      # 3) 蝨ｨ蠎ｫ遘ｻ蜍輔↑縺ｩ縺ｮ螟画峩繧偵さ繝溘ャ繝・
      - name: Commit moved/posted changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "move posted items & logs"
          git push
