name: Update RSS for Dialect Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # 30分ごと
  workflow_dispatch:

permissions:
  contents: write   # ← push 権限を付与

jobs:
  rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Validate JSON
        run: node validator.js

      - name: Run script
        run: node index.js   # ← リトライ外してシンプルに実行

      - name: Commit updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts.xml last.json log.json
          git commit -m "Update RSS feed" || echo "No changes"
          git push
